### ISSUE TITLE
Rename `window.view` to `window.visualViewport`

### ISSUE THREAD

**Issue by bokand** [bokand/ViewportAPI#42]
We originally changed this the other way in the context of #35 but this has compatibility issues. There's a non-trivial number of pages using a global `view` which could cause them to break if we add this. Last I checked `visualViewport` was unused in the HTTPArchive and so has much less risk.

The original complaint was that it's cumbersome and "java-like". IMO, it actually fits in well with other `window` properties like `sessionStorage`, `localStorage`, and `devicePixelRatio`. Worst-case, authors can always alias it to something more convenient.

@hexalys, @dbaron, any concerns?

**Comment by RByers** [comment]
+1 that `window.view` appears to risky from a web compat perspective to ship.  I have no preference on the name as long as we don't have examples of sites hitting it.

@bokand can you please add details of the compat issues (the failure you saw, and your HTTP Archive data)?

**Comment by bokand** [comment]
Sure. The failure I found in the Chromium repo comes from the Khronos WebGL conformance tests we import:

https://github.com/KhronosGroup/WebGL/blob/master/sdk/tests/conformance/typedarrays/data-view-crash.html

Other tests in that directory also use a global `var view` but it shadows `window.view` so it doesn't cause an issue in those tests. Enabling the API causes the above test to fail since it sees that `view` is defined so it assumes it must be the DataView and tries to call a method on it, not realizing it's actually doing so on the VisualViewport object.

From HTTPArchive (these are mostly upper bounds as it's hard to glean scope from a string match):

I looked for declarations of `view` without setting a value which is potentially troublesome using this query: `SELECT page, url, body FROM [httparchive:har.2017_06_01_chrome_requests_bodies] WHERE REGEXP_MATCH(body, '.*var\\s*view\\s*;.*')`

This returned 519 / 16,517,787 results from `httparchive:har.2017_06_01_chrome_requests_bodies`
And 428 / 15,408,366 results from `httparchive:har.2017_06_01_android_requests_bodies`

I looked for uses of `window.view` with this query:
`SELECT page, url, body FROM [httparchive:har.2017_06_01_chrome_requests_bodies] WHERE REGEXP_MATCH(body, '.*window\\.view[^A-Za-z0-9_].*')`

This returned 98 / 16,517,787 results from `httparchive:har.2017_06_01_chrome_requests_bodies`
And 82 / 15,408,366 results from `httparchive:har.2017_06_01_android_requests_bodies`

**Comment by hexalys** [comment]
`view` was ideal. I am not too surprised now that you mention potential conflicts. That said if they use 'view'. It would just override the object no? and wouldn't necessarily create any breakage...

While not a fan of `visualViewport`. I don't have any better alternative to suggest.

**Comment by hexalys** [comment]
Or maybe `innerView` would be a preference, now that I think about. But probably for an alias at this point.

**Comment by bokand** [comment]
If the author sets a value to `view` then there is generally no problem (although this may interfere with a library using it). The issues start when some component checks `window.view` and uses it prior to setting it (e.g. a repeated timeout querying it while an XHR sets it in the background) . In that case, the type of the object will be unexpected.

I'm personally partial to `visualViewport` as it has a clearly established meaning at this point, doesn't conflict with anything and provides no ambiguity or opportunity for misunderstanding. Authors can always do something like: `window.view = window.visualViewport` if they're so inclined.

**Comment by bokand** [comment]
@dbaron [mentioned in the TAG issue](https://github.com/w3ctag/design-reviews/issues/172#issuecomment-311193333) that it's ok with him and that it probably didn't come up in TAG review. If others have reasons against this I'm happy to hear but in the mean time I'm going to proceed with this change.

**Comment by bokand** [comment]
Changes to spec and repo made in 0afa8d6537f45af90e29a4b8b7637e7a1f07aa85. I've also updated WPT and Chromium implementation.
