### ISSUE TITLE
changing visual viewport dynamically

### ISSUE THREAD

**Issue by AliBahramiEhsan** [bokand/ViewportAPI#50]
As in [stackoverflow](https://stackoverflow.com/questions/47155789/dynamicly-change-visual-viewport-in-mobile-devices),  I think of changing visual viewport dynamicly. This will be useful in routings, when user changes its position in a SPA.
As I searched a lot, I found out these parameters are read only (visual viewport height and width) but there are changing according to focus or user behavior. So, changing it by code is necessary.
Thanks for any help, or information.

**Comment by bokand** [comment]
Could you provide a motivating use case? Opening up the properties to writing is an interesting idea but I'd like to understand what the real world use cases might be before we invest time into that.

**Comment by AliBahramiEhsan** [comment]
Dynamic change in visual viewport can be interesting. You can change the zoom in the area in different parts of webpage. Also you can create a sticky effect, which leads users behavior to a robust view of things. 
This can be a new way to navigate in the web, without closing freedom of users, and controlling what they see.
