### ISSUE TITLE
Should window.visualViewport be null if there's no associated browsing context?

### ISSUE THREAD

**Issue by alijuma** [bokand/ViewportAPI#51]
Several Window APIs currently return null when there's no associated browsing context (e.g., this happens when we have a window object corresponding to an iframe element that has been removed from the DOM). See calls to "IsCurrentlyDisplayedInFrame" in LocalDOMWindow.cpp in Blink for examples.

Should window.visualViewport behave the same way? Currently in Blink, it's non-null even when there's no associated browsing context, but the question of whether it should really be null came up in a WebKit code review: https://bugs.webkit.org/show_bug.cgi?id=179385#c7

**Comment by bokand** [comment]
Yeah, it doesn't make much sense to return a visualViewport for a detached iframe. We already return 0 for all the DOMVisualViewport accessors in that case. I'll make the change in Blink and add that to the spec.
