### ISSUE TITLE
Should specify the order of resize event with DOMWindow's resize event

### ISSUE THREAD

**Issue by rniwa** [bokand/ViewportAPI#65]
This specification doesn't specify whenever resize event on visual viewport is dispatched before or after resize event on window object but it should.

**Comment by rniwa** [comment]
According to [my testing](https://gist.github.com/rniwa/6dacd1c9cb8a28daff086d58830ddd88), resize event on visualViewport fires before the one on window in Chrome whereas it fires on window first then visualViewport in Safari.

**Comment by rniwa** [comment]
@smfr

**Comment by emilio** [comment]
cc @hiikezoe / @theres-waldo

**Comment by hiikezoe** [comment]
I agree it should define the order, but I have no idea which one should be prior to the other.  In Firefox window resize event is fired before visual viewport one.

**Comment by rniwa** [comment]
@hiikezoe : Sounds like both Firefox & Safari fire on window first then visual viewport. So spec'ing that behavior seems sensible unless someone from Google / Blink object to that.

**Comment by hiikezoe** [comment]
cc @bokand

**Comment by bokand** [comment]
I can't think if a reason to prefer one or the other. Absent some good reason or compat issues I'm fine to change Blink to fire the viewport resize after the window resize and spec that.

I've filed https://crbug.com/1016210 to track the Blink change.

**Comment by rniwa** [comment]
I guess another thing to check is whether the order matches scroll event’s ordering as well. It would be weird to be different between the two.

**Comment by hiikezoe** [comment]
In Firefox firing scroll event is the same order, scroll event on GlobalEventHandler is fired before visual viewport one.

**Comment by rniwa** [comment]
Splitting scroll event issue to https://github.com/WICG/visual-viewport/issues/66 since that case is more complicated.

**Comment by rniwa** [comment]
@annevk : should we update the HTML spec to add a new separate step for visual viewport API? Or should we specify the relative ordering with the regular resize event in visual viewport API?

**Comment by annevk** [comment]
I think there are two reasonable long term approaches:

1. Patch HTML.
2. Patch https://drafts.csswg.org/cssom-view/#run-the-resize-steps.

Monkey patching is a reasonable temporary solution, until your draft/standard gains more acceptance. (And ideally even in that stage there's minimally an upstream issue to inform others of the monkey patching.)

**Comment by bokand** [comment]
The ordering issue has been fixed in Blink so all engines are aligned now - I'm adding a WPT for this.

#80 attempts to fix the issue in spec text by monkey patching the resize/scroll steps in CSSOM-View.
