### ISSUE TITLE
Safari 15 supports visual viewport but it's useless because the spec missed an important thing

### ISSUE THREAD

**Issue by 205g0** [bokand/ViewportAPI#79]
Safari 15 does not trigger a `resize` event when the virtual keyboards is coming up. So, you just read from a stale or undefined `window.visualViewport`. Do I miss something or how does it come that the spec missed this crucial part? 😶

**Comment by 205g0** [comment]
For others driving by and as note to myself: Another problem I've observed is that Safari does not set the, e.g., `.height` when the virtual keyboard is again going down. I tested this with a `setInterval(() => console.log(window.visualViewport), 1000)`. While it changes once the keyboard is up, it does not change back again when the keyboard is down.  🙄

Since this feature is GA on all new iPhones but completely broken., who is the right person to address this to? The spec creators, Apple, who?

**Comment by karlcow** [comment]
@205g0   could you create a self-contained test case where we can compare in between mobile browsers.

**Comment by 205g0** [comment]
Open https://1lism.csb.app/ on your smartphone/mobile browsers and test by tapping the input field at the top. It works with Android Chrome, Android Firefox but not with iOS Safari (15).

You find the respective source at https://codesandbox.io/s/eager-tesla-1lism?file=/index.html

What would be the process? Someone is extending the spec and then, asks Apple to align or how would it work? Let me know if you need more.

**Comment by chongruei** [comment]
> For others driving by and as note to myself: Another problem I've observed is that Safari does not set the, e.g., `.height` when the virtual keyboard is again going down. I tested this with a `setInterval(() => console.log(window.visualViewport), 1000)`. While it changes once the keyboard is up, it does not change back again when the keyboard is down. 🙄
> 
> Since this feature is GA on all new iPhones but completely broken., who is the right person to address this to? The spec creators, Apple, who?

same with me. the height couldn't update truly value immediately.

**Comment by 205g0** [comment]
@karlcow Karl, any news? If you don't have time, pls let us know who are the right people as asked previously.

**Comment by bokand** [comment]
This sounds like a bug in WebKit. You could try filing a bug on https://bugs.webkit.org/. @rniwa might also know whether this is intentional or not.

**Comment by bokand** [comment]
This is the same as #78. This is something Safari would have to change, see https://bugs.webkit.org/show_bug.cgi?id=229876

I don't think there's an issue on the visual-viewport here so I'm going to close this.
